export { buttonPlayInit } from './buttonPlay'
export { gameSceneInit } from './gameScene'
export { creditsPanel } from './creditsPanel'
export { AnimationsGameArea } from './AnimationGameArea'
export { areaForAnimation } from './AreaForAnimation'
export { createRandomGameArea } from './createRandomGameArea.js'